# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PenCake' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PenCake

  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
end
